//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNameSpace {
    using System;
    
    
    public sealed class SomethingGood {
        
        public int firstProperty;
        
        public int secondProperty;
        
        public float thirdProperty;
        
        public int FirstProperty {
            get {
                return this.firstProperty;
            }
            set {
                this.firstProperty = value;
            }
        }
        
        public int SecondProperty {
            get {
                return this.secondProperty;
            }
            set {
                this.secondProperty = value;
            }
        }
        
        public float ThirdProperty {
            get {
                return this.thirdProperty;
            }
            set {
                this.thirdProperty = value;
            }
        }
    }
}
